name: 'Codium PR Agent'
description: 'Summarize, review and suggest improvements for pull requests'
branding:
  icon: 'award'
  color: 'green'
runs:
  using: 'docker'
  image: 'ghcr.io/sofatutor/pr-agent:sofatutor-kids'
