FROM python:3.10 as base

ENV OPENAI_API_KEY=${OPENAI_API_KEY} \
    BITBUCKET_BEARER_TOKEN=${BITBUCKET_BEARER_TOKEN} \
    BITBUCKET_PR_ID=${BITBUCKET_PR_ID} \
    BITBUCKET_REPO_SLUG=${BITBUCKET_REPO_SLUG} \
    BITBUCKET_WORKSPACE=${BITBUCKET_WORKSPACE}


WORKDIR /app
ADD pyproject.toml .
ADD requirements.txt .
RUN pip install . && rm pyproject.toml requirements.txt
ENV PYTHONPATH=/app
ADD pr_agent pr_agent
ADD bitbucket_pipeline/entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
