blank_issues_enabled: false
version: 0.1
contact_links:
  - name: Discussions
    url: https://github.com/qodo-ai/pr-agent/discussions
    about: GitHub Discussions

  - name: Discord community
    url: https://discord.com/channels/1057273017547378788/1126104260430528613
    about: Join our discord community
