name: Test a PR
title: 'Sweep: '
description: Generate tests for components that changed in a PR
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: The new endpoint should use the ... class from ... file because it contains ... logic
