name: Document a PR
title: 'Sweep: '
description: Generate Docstrings for relevant components in a PR
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: We are migrating this function to ... version because ...
