name: Regular Issue
title: 'Sweep: '
description: "A standard issue"
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details about the bug
      placeholder: The bug might be in ... file
  - type: textarea
    id: description2
    attributes:
      label: ttt
      description: ttt
      placeholder: ttt
  - type: dropdown
    id: download
    attributes:
      label: How did you download the software?
      options:
        - Homebrew
        - MacPorts
        - apt-get
        - Built from source
    validations:
      required: true
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: What kinds of cats do you like?
      description: You may select more than one.
      options:
        - label: Orange cat (required. Everyone likes orange cats.)
          required: true
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Whenever I visit the user account page (1-2 times a week)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
