name: Build-and-test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: dockerx
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: login
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build
        name: Build and push docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.github_action
          push: true
          tags: ghcr.io/inside-ai-me/pr-agent:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: base
