name: Build-and-test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: dockerx
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: build
        name: Build dev docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.github_action
          push: false
          load: true
          tags: Inside-AI-me/pr-agent:latest
          cache-from: type=gha,scope=dev
          cache-to: type=gha,mode=max,scope=dev
          target: test
